In [15]:
import requests
import os
import shutil

In [3]:
years = list(range(1991,2021))

In [3]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

for year in years:
    url = url_start.format(year)
    
    data = requests.get(url)
    
    with open("mvp/{}.html".format(year), "w+", encoding ="utf-8") as f:
        f.write(data.text)

In [6]:
from bs4 import BeautifulSoup

In [24]:

with open("mvp/1991.html", encoding="utf-8") as f:
    page = f.read()
    
soup = BeautifulSoup(page, 'html.parser')
soup.find('tr', class_="over_header").decompose()

In [6]:
mvp_table = soup.find_all(id="mvp")[0]

In [2]:
import pandas as pd

In [8]:
mvp_1991 = pd.read_html(str(mvp_table))[0]

In [9]:
mvp_1991.head(1)

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,31.5,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321

In [10]:
mvp_1991["Year"] = 1991

In [11]:
mvp_1991.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [12]:
dfs = []
for year in years:
    with open("mvp/{}.html".format(year),encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="over_header").decompose()
    mvp_table = soup.find_all(id="mvp")[0]
    mvp_df = pd.read_html(str(mvp_table))[0]
    mvp_df["Year"] = year
    dfs.append(mvp_df)

In [13]:
mvps = pd.concat(dfs)

mvps.tail()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
7,8,Damian Lillard,29,POR,0.0,23.0,1010,0.023,66,37.5,...,4.3,8.0,1.1,0.3,0.463,0.401,0.888,11.6,0.225,2020
8,9,Nikola Jokić,24,DEN,0.0,18.0,1010,0.018,73,32.0,...,9.7,7.0,1.2,0.6,0.528,0.314,0.817,9.8,0.202,2020
9,10,Pascal Siakam,25,TOR,0.0,17.0,1010,0.017,60,35.2,...,7.3,3.5,1.0,0.9,0.453,0.359,0.792,5.4,0.123,2020
10,11,Jimmy Butler,30,MIA,0.0,9.0,1010,0.009,58,33.8,...,6.7,6.0,1.8,0.6,0.455,0.244,0.834,9.0,0.221,2020
11,12,Jayson Tatum,21,BOS,0.0,1.0,1010,0.001,66,34.3,...,7.0,3.0,1.4,0.9,0.450,0.403,0.812,6.9,0.146,2020

In [14]:
mvps.to_csv("mvps.csv")

In [18]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

for year in years:
    url = player_stats_url.format(year)
    
    data = requests.get(url)
    
    with open("player/{}.html".format(year), "w+",encoding="utf-8") as f:
        f.write(data.text)

In [5]:
import os
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
import time

In [12]:
service = Service("C:\\Users\\luked\\Desktop\\chromedriver.exe")
driver = webdriver.Chrome(service=service)

In [19]:
year = 1991 
url = player_stats_url.format(year)

driver.get(url)
driver.execute_script("window.scrollTo(1,10000)")
time.sleep(2)

html = driver.page_source

In [46]:
with open("player/{}.html".format(year), "w+",encoding="utf-8") as f:
    f.write(html)

In [18]:
for year in years:
    url = player_stats_url.format(year)

    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)

    html = driver.page_source
    with open("player/{}.html".format(year), "w+",encoding="utf-8") as f:
        f.write(html)

In [29]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\luked\anaconda3\lib\site-packages (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\luked\anaconda3\lib\site-packages (from beautifulsoup4) (2.4)

In [29]:
dfs = []

for year in years:
    with open("player/{}.html".format(year), "r", encoding="utf-8") as f:
        page = f.read()

    soup = BeautifulSoup(page, 'html.parser')
    thead = soup.find('tr', class_="thead")

    if thead:
        thead.decompose()
        player_table = soup.find_all(id="per_game_stats")[0]
        player = pd.read_html(str(player_table))[0]
        player["Year"] = year
        dfs.append(player)
    else:
        print("The element 'tr' with class 'thead' was not found in the HTML for year {}.".format(year))
        continue

In [30]:
players = pd.concat(dfs)

In [31]:
players.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [32]:
players

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,525,Trae Young,PG,21,ATL,60,60,35.3,9.1,20.8,...,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6,2020
672,526,Cody Zeller,C,27,CHO,58,39,23.1,4.3,8.3,...,2.8,4.3,7.1,1.5,0.7,0.4,1.3,2.4,11.1,2020
673,527,Tyler Zeller,C,30,SAS,2,0,2.0,0.5,2.0,...,1.5,0.5,2.0,0.0,0.0,0.0,0.0,0.0,1.0,2020
674,528,Ante Žižić,C,23,CLE,22,0,10.0,1.9,3.3,...,0.8,2.2,3.0,0.3,0.3,0.2,0.5,1.2,4.4,2020
675,529,Ivica Zubac,C,22,LAC,72,70,18.4,3.3,5.3,...,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,2020

In [33]:
players.to_csv("players.csv")

In [9]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [22]:
for year in years:
    url = team_stats_url.format(year)

    data = requests.get(url)

    with open("team/{}.html".format(year), "w+",encoding="utf-8") as f:
        f.write(data.text)

In [42]:
dfs = []
for year in years:
    with open("team/{}.html".format(year),encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(str(e_table))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    dfs.append(e_df)
    
    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(str(w_table))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    dfs.append(w_df)

In [39]:
teams = pd.concat(dfs)

In [43]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0   56  26  .683     —  111.5  105.7   5.22  1991       Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991   Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991      New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
..  ..  ..   ...   ...    ...    ...    ...   ...                   ...
13  44  28  .611     —  117.8  114.8   3.13  2020      Houston Rockets*
14  43  32  .573   2.5  117.0  112.1   4.87  2020     Dallas Mavericks*
15  34  39  .466  10.5  112.6  113.7  -0.91  2020     Memphis Grizzlies
16  32  39  .451  11.5  114.1  115.2  -0.65  2020     San Antonio Spurs
17  30  42  .417  14.0  115.8  117.1  -0.55  2020  New Orleans Pelicans

[998 rows x 9 columns]

In [44]:
teams.to_csv("teams.csv")